id: I92C416FE
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T03:35:26+00:00'
last_modified: '2022-06-08T11:55:04.790335+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2PD19192
  title: 'སོག་པོ་མཁས་པ་རྣམས་ཀྱི་བོད་སྐད་དུ་བརྩམས་པའི་གསུང་འབུམ་དཀར་ཆག

    '
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    338D:
      image_group_id: I2PD19338
      title: ''
      total_pages: 500
      order: 1
      base_file: 338D.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
