id: P009563
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-19 20:38:16.178537
source_metadata:
  id: bdr:W2PD19192
  title: 'སོག་པོ་མཁས་པ་རྣམས་ཀྱི་བོད་སྐད་དུ་བརྩམས་པའི་གསུང་འབུམ་དཀར་ཆག

    '
  author: ''
  volumes:
    5732b904941a44819d0956e4b0738a0e:
      image_group_id: I2PD19338
      title: ''
      volume_number: 1
      total_pages: 500
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
